# Generated by Django 5.2.4 on 2025-12-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='moodlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
