# Generated by Django 5.2.4 on 2025-12-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker_app', '0004_alter_profile_avatar_alter_profile_last_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.jfif', upload_to='avatars/'),
        ),
    ]
