# Generated by Django 5.2.4 on 2025-12-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker_app', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodlog',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='moodlog',
            name='tag_emoji',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
