# Generated by Django 5.2.4 on 2025-12-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker_app', '0006_moodlog_tag_moodlog_tag_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodlog',
            name='tag_emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
